name: calorie_mate
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.0.3
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.4
  flutter_launcher_icons: ^0.9.0
  provider: ^5.0.0
  rflutter_alert: ^2.0.2
  modal_progress_hud: ^0.1.3
  flutter_icons: ^1.1.0
  keyboard_avoider: ^0.1.2

flutter_icons: 
  image_path: "assets/images/CMIcon.png"
  android: true



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
  - assets/images/onboarding0.png
  - assets/images/onboarding1.png
  - assets/images/onboarding2.png
  - assets/images/meal_onbrd.png
  - assets/images/food_onbrd.png
  - assets/images/workout_onbrd.png
  - assets/images/CMLogo.png
  - assets/images/CMLogoDark.png
  - assets/images/CMLogoDarkHigh.png
  - assets/images/CMIcon.png
  - assets/images/circle_drop.png
  - assets/images/google.png



  fonts:
    # - family: CM Sans Serif
    #   fonts:
    #     - asset: assets/fonts/cm_sans_serif_2012.ttf
    #     - asset: assets/fonts/ProximaNova-Regular.otf
    #     - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
        - asset: assets/fonts/ProximaNova-Bold.otf
          weight: 700
        - asset: assets/fonts/ProximaNova-Extrabold.otf
          weight: 800
        - asset: assets/fonts/ProximaNova-Black.otf
          weight: 900

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
