name: calorie_mate
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.0.3
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.4
  flutter_launcher_icons: ^0.9.0
  provider: ^4.3.2
  http: any
  intl: any
  image_picker: ^0.7.4
  rflutter_alert: ^2.0.2
  page_transition: ^1.1.4
  simple_animations: ^2.2.1
  transparent_image: ^1.0.0
  grouped_buttons: ^1.0.4
  flutter_swiper: ^1.1.6
  flutter_staggered_grid_view: ^0.4.0
  rubber: ^1.0.0
  numberpicker: ^2.1.1
  intl_phone_field: ^2.0.0
  flare_splash_screen: ^2.1.2
  argon_buttons_flutter: ^1.0.6
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.0.0
  rxdart: ^0.23.0
  equatable: ^2.0.0
  flutter_bloc: ^3.2.0
  url_launcher: ^6.0.3
  google_fonts: ^2.0.0
  flare_flutter:
  bot_toast: ^4.0.1
  validate: ^1.7.0
  modal_progress_hud: ^0.1.3
  awesome_dialog: ^1.3.2
  cupertino_icons: ^1.0.2
  validators: ^3.0.0
  flutter_icons:
  flutter_svg:
  firebase_storage: ^10.0.1
  firebase_database: ^7.1.2
  fl_chart: ^0.20.1
  syncfusion_flutter_charts: ^19.3.43
  auto_size_text: ^2.1.0
  shared_preferences: ^2.0.7

flutter_icons:
  image_path: 'assets/images/CMIcon.png'
  android: true

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
